name: test
description: Get help with writing tests.
version: 1.2.8
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dash_agent:
    path: /Users/samyak/Documents/commanddash/commanddash/dash_agent/

dev_dependencies:
  lints: ^3.0.0
