name: test
description: Get help with writing tests.
version: 1.2.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dash_agent: ^ 0.1.1

dev_dependencies:
  lints: ^3.0.0
