name: flame
description: Get help with flame framework
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  dash_agent: ^0.3.0
  http: ^1.2.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
