name: gemini
description: Build AI apps with Gemini APIs and client SDKs
version: 1.0.95
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dash_agent: ^0.3.0
  http: ^1.2.0
  xml: ^6.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
