name: flutter
description: Get Flutter specific help like asking questions across documentation.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  dash_agent:
    path: /Users/yogesh/Development/org.welltested/commanddash/dash_agent
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
