name: ai_sdk
description: Vercel AI SDK helps you build AI chat experiences in your React apps.
version: 1.0.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dash_agent: ^0.2.1
  http:
  xml: ^6.5.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
